sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.8.3
before_install:
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-ce
script:
  - make all
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin;
      make deploy;
    elif [ "${TRAVIS_BRANCH}" == "1.7" ]; then
      echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin;
      DOCKER_HUB_TAG="${DOCKER_HUB_1_7_TAG}" make deploy;
    fi
notifications:
  email:
    recipients:
      - aditya@portworx.com
      - piyush@portworx.com
      - jv@portworx.com
      - harsh@portworx.com
      - rohit@portworx.com
    on_success: change
    on_failure: always
